all : client server_select server_poll

client : client.cpp
	g++ -o client client.cpp

server_select: server_select.cpp
	g++ -o server_select server_select.cpp

server_poll: server_poll.cpp
	g++ -o server_poll server_poll.cpp

